from .dashbord_admin import views as dashbord_admin
from .pilihan_layanan import views as pilihan_layanan
from .lihat_data_ppdb import views as lihat_data_ppdb
from .lihat_data_mutasi import views as lihat_data_mutasi
from .lihat_data_pip import views as lihat_data_pip
from .lihat_data_kjp import views as lihat_data_kjp
from .lihat_data_administrasi_sekolah import views as lihat_data_administrasi_sekolah
from .lihat_data_kunjungan_instansi import views as lihat_data_kunjungan_instansi
from .hapus_data_ppdb import views as hapus_data_ppdb
from .hapus_data_mutasi import views as hapus_data_mutasi
from .hapus_data_pip import views as hapus_data_pip
from .hapus_data_kjp import views as hapus_data_kjp
from .hapus_data_administrasi_sekolah import views as hapus_data_administrasi_sekolah
from .hapus_data_kunjungan_antar_instansi import views as hapus_data_kunjungan_antar_instansi
from .data_siswa import views as data_siswa
from .detail_siswa import views as detail_siswa
from .data_guru import views as data_guru
from .data_berita import views as data_berita
from .template_lulus import views as template_lulus
from .detail_berita import views as detail_berita
from .detail_guru import views as detail_guru
from .hapus_berita import views as hapus_berita
from .hapus_guru import views as hapus_guru
from .hapus_siswa import views as hapus_siswa
from .table_kjp import views as table_kjp
from .data_feedbacks_user import views as data_feedbacks_user
from .hapus_feedback import views as hapus_feedback
from .data_tendik import views as data_tendik
from .detail_tendik import views as detail_tendik
from .hapus_tendik import views as hapus_tendik
from .arsip_guru import views as arsip_guru
from .detail_arsip_guru import views as detail_arsip_guru
from .hapus_arsip_guru import views as hapus_arsip_guru
from .hapus_data_arsip_guru import views as hapus_data_arsip_guru
from .pilih_arsip_ijazah import views as pilih_arsip_ijazah
from .arsip_ijazah import views as arsip_ijazah
from .hapus_data_arsip_ijazah import views as hapus_data_arsip_ijazah
# from .table_kjp_baru import views as table_kjp_baru
# from .hapus_data_kjp_baru import views as hapus_data_kjp_baru
from .download_kk import views as download_kk
from .download_ktp import views as download_ktp
