from .dashbord_admin import views as dashbord_admin
from .pilihan_layanan import views as pilihan_layanan
from .lihat_data_ppdb import views as lihat_data_ppdb
from .lihat_data_mutasi import views as lihat_data_mutasi
from .lihat_data_pip import views as lihat_data_pip
from .lihat_data_kjp import views as lihat_data_kjp
from .lihat_data_administrasi_sekolah import views as lihat_data_administrasi_sekolah
from .lihat_data_kunjungan_instansi import views as lihat_data_kunjungan_instansi
from .hapus_data_ppdb import views as hapus_data_ppdb
from .hapus_data_mutasi import views as hapus_data_mutasi
from .hapus_data_pip import views as hapus_data_pip
from .hapus_data_kjp import views as hapus_data_kjp
from .hapus_data_administrasi_sekolah import views as hapus_data_administrasi_sekolah
from .hapus_data_kunjungan_antar_instansi import views as hapus_data_kunjungan_antar_instansi