from .login_siswa import auth as login_siswa
from .login_admin import auth as login_admin
from .logout import auth as logout
from .input_data_siswa import auth as input_data_siswa
from .update_data_siswa import auth as update_data_siswa
from .update_data_per_siswa import auth as update_data_per_siswa
from .buat_akun_siswa import auth as buat_akun_siswa
from .input_berita import auth as input_berita
from .input_data_guru import auth as input_data_guru
from .upload_data_guru import auth as upload_data_guru
from .update_data_guru import auth as update_data_guru