from .login_siswa import auth as login_siswa
from .login_admin import auth as login_admin
from .logout import auth as logout
from .input_data_siswa import auth as input_data_siswa
from .update_data_siswa import auth as update_data_siswa
from .update_data_per_siswa import auth as update_data_per_siswa
from .buat_akun_siswa import auth as buat_akun_siswa
from .input_berita import auth as input_berita
from .input_data_guru import auth as input_data_guru
from .upload_data_guru import auth as upload_data_guru
from .update_data_guru import auth as update_data_guru
from .layanan_ppdb import auth as layanan_ppdb
from .layanan_mutasi import auth as layanan_mutasi
from .layanan_pip import auth as layanan_pip
from .layanan_kjp import auth as layanan_kjp
from .layanan_administrasi_sekolah import auth as layanan_administrasi_sekolah
from .layanan_kunjungan_antar_instansi import auth as layanan_kunjungan_antar_instansi